### ISSUE TITLE
android_cv_bridge_tutorial not running

### ISSUE THREAD

**Issue by kejriwalnishant1990** [talregev/android_cv_bridge#1]
I am trying to run your tutorial on android_cv_bridge but it is throwing following error.
I am subscribing the image topic(/camera/rgb/image_color) from kinect in android phone. I ahve made my laptop as master and android phone as client.

org.ros.android.android_tutorial_cv_bridge E/roid_tutorial_cv_bridge﹕ cv_bridge exception: Unrecognized image encoding [bgr8]
org.ros.android.android_tutorial_cv_bridge E/art﹕ No implementation found for void org.opencv.core.Mat.n_delete(long) (tried Java_org_opencv_core_Mat_n_1delete and Java_org_opencv_core_Mat_n_1delete__J)
org.ros.android.android_tutorial_cv_bridge E/System﹕ Uncaught exception thrown by finalizer
org.ros.android.android_tutorial_cv_bridge E/System﹕ java.lang.UnsatisfiedLinkError: No implementation found for void org.opencv.core.Mat.n_delete(long) (tried Java_org_opencv_core_Mat_n_1delete and Java_org_opencv_core_Mat_n_1delete__J)
            at org.opencv.core.Mat.n_delete(Native Method)
            at org.opencv.core.Mat.finalize(Mat.java:2475)
            at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:191)
            at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:174)
            at java.lang.Thread.run(Thread.java:818)

**Comment by talregev** [comment]
I will check it.
Can you past an example code here?

**Comment by kejriwalnishant1990** [comment]
@Override
  public void onStart(ConnectedNode connectedNode) {
      this.node = connectedNode;
      final org.apache.commons.logging.Log log = node.getLog();
      imageSubscriber = node.newSubscriber("/camera/rgb/image_color", Image._TYPE);
      imageSubscriber.addMessageListener(new MessageListener<Image>() {
          @Override
          public void onNewMessage(Image message) {
              CvImage cvImage;

```
          try {
                cvImage = CvImage.toCvCopy(message,"bgr8");
              System.out.print(cvImage.encoding);
          } catch (Exception e) {
              log.error("cv_bridge exception: " + e.getMessage());
              return;
          }
          if (cvImage.image.rows() > 60 && cvImage.image.cols() > 60)
              Core.circle(cvImage.image, new Point(50, 50), 10, new Scalar(255,0,0));

          System.out.print("Size of the image subscribed \t");
          System.out.print(cvImage.image.rows());
          System.out.print(cvImage.image.cols());


          Imshow im = new Imshow("Subscribed image");
          im.showImage(cvImage.image);
          try {
              im.wait(200);
          } catch (InterruptedException e) {
              e.printStackTrace();
          }


     }
  });

  Log.i(TAG, "called onStart");
```

  }

**Comment by talregev** [comment]
This code not finish yet :) 
I will check it.

**Comment by kejriwalnishant1990** [comment]
I have just pasted OnStart method.... Should I paste other methods .. although I havent changed any thing in other parts.

**Comment by kejriwalnishant1990** [comment]
Hi talregev, 

I found that there is some problem with image encodings in cv_bridge. Any update on it?

**Comment by kejriwalnishant1990** [comment]
Hi talregev,

I found that there is some problem with image encodings in cv_bridge. Any update on it?

**Comment by kejriwalnishant1990** [comment]
Any update of image_encoding issue?

**Comment by talregev** [comment]
I have updated the cv_bridge library. the `CvImage` should work now.
There still issues with `CvCompressedImage`. It will take time to solve.

**Comment by kejriwalnishant1990** [comment]
Should i download the code again or i can do small change and it will work?

**Comment by talregev** [comment]
git pull?

**Comment by kejriwalnishant1990** [comment]
okk... i will pull the repo again.

**Comment by talregev** [comment]
If you like my library, please help to update the wiki. thanks!

**Comment by kejriwalnishant1990** [comment]
Once this subscriber works, i will work with you to update the code and wiki.

**Comment by kejriwalnishant1990** [comment]
You have set android 23 as target sdk? Is it necessary to use 23 SDK version?

**Comment by talregev** [comment]
Not necessary, but i like to work on the latest SDK and compiler. 
But the program will work on older devise also. (from Gingerbread 2.3.\* (sdk 10)  and above. )

**Comment by kejriwalnishant1990** [comment]
i am getting this error while subscribing the image:

9271-9580/org.ros.android.android_tutorial_cv_bridge E/art﹕ No implementation found for long org.opencv.core.Mat.n_Mat(int, int, int) (tried Java_org_opencv_core_Mat_n_1Mat and Java_org_opencv_core_Mat_n_1Mat__III)
08-21 23:13:27.490    9271-9580/org.ros.android.android_tutorial_cv_bridge E/AndroidRuntime﹕ FATAL EXCEPTION: pool-1-thread-14
    Process: org.ros.android.android_tutorial_cv_bridge, PID: 9271
    java.lang.UnsatisfiedLinkError: No implementation found for long org.opencv.core.Mat.n_Mat(int, int, int) (tried Java_org_opencv_core_Mat_n_1Mat and Java_org_opencv_core_Mat_n_1Mat__III)
            at org.opencv.core.Mat.n_Mat(Native Method)

**Comment by talregev** [comment]
Did you change the target sdk?

**Comment by kejriwalnishant1990** [comment]
yes i made it 15 for android_tutorial_cv_bridge.

**Comment by talregev** [comment]
please leave the target sdk as is.

**Comment by kejriwalnishant1990** [comment]
ok let me check.

**Comment by talregev** [comment]
please pull from git the changes and not do it by yourself.

**Comment by kejriwalnishant1990** [comment]
If i dont make any change, i get following error : Unfotunately. cv_bridge Tutorial has stopped.
In logcat, following error is displayed:
 13084-13115/org.ros.android.android_tutorial_cv_bridge E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #1
    Process: org.ros.android.android_tutorial_cv_bridge, PID: 13084
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:304)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
            at android.os.Handler.<init>(Handler.java:200)
            at android.os.Handler.<init>(Handler.java:114)
            at android.app.Dialog.<init>(Dialog.java:108)
            at android.app.AlertDialog.<init>(AlertDialog.java:125)
            at android.app.AlertDialog$Builder.create(AlertDialog.java:973)
            at org.opencv.android.BaseLoaderCallback.onPackageInstall(BaseLoaderCallback.java:90)
            at org.opencv.android.AsyncServiceHelper.InstallService(AsyncServiceHelper.java:116)
            at org.opencv.android.AsyncServiceHelper.initOpenCV(AsyncServiceHelper.java:32)
            at org.opencv.android.OpenCVLoader.initAsync(OpenCVLoader.java:89)
            at org.ros.android.android_tutorial_cv_bridge.MainActivity.onResume(MainActivity.java:160)
            at org.ros.android.android_tutorial_cv_bridge.MainActivity.init(MainActivity.java:96)
            at org.ros.android.RosActivity$2.doInBackground(RosActivity.java:204)
            at org.ros.android.RosActivity$2.doInBackground(RosActivity.java:201)
            at android.os.AsyncTask$2.call(AsyncTask.java:292)

**Comment by talregev** [comment]
Try to make every sub-module to target sdk 15, and tell me what you get.

**Comment by kejriwalnishant1990** [comment]
If i comment this part, then code does not exit suddenly.
// try {
//                    cvImage = CvImage.toCvCopy(message);
//                } catch (Exception e) {
//                    log.error("cv_bridge exception: " + e.getMessage());
//                    return;
//                }

For which module should i made target sdk 15? cv_bridge_tutorial???

**Comment by kejriwalnishant1990** [comment]
android_cv_bridge_tutorial has already targetSdk as 15.

**Comment by talregev** [comment]
for every sub-moudle:
android_cv_bridge_tutorial already in 15.

**Comment by talregev** [comment]
opencv, opencv3, cv_bridge, module and the rest.

**Comment by kejriwalnishant1990** [comment]
Still same error:

19717-19948/org.ros.android.android_tutorial_cv_bridge E/art﹕ No implementation found for long org.opencv.core.Mat.n_Mat(int, int, int) (tried Java_org_opencv_core_Mat_n_1Mat and Java_org_opencv_core_Mat_n_1Mat__III)
08-21 23:40:32.422  19717-19948/org.ros.android.android_tutorial_cv_bridge E/AndroidRuntime﹕ FATAL EXCEPTION: pool-1-thread-13
    Process: org.ros.android.android_tutorial_cv_bridge, PID: 19717
    java.lang.UnsatisfiedLinkError: No implementation found for long org.opencv.core.Mat.n_Mat(int, int, int) (tried Java_org_opencv_core_Mat_n_1Mat and Java_org_opencv_core_Mat_n_1Mat__III)
            at org.opencv.core.Mat.n_Mat(Native Method)
            at org.opencv.core.Mat.<init>(Mat.java:477)
            at cv_bridge.CvImage.matFromImage(CvImage.java:351)
            at cv_bridge.CvImage.toCvCopy(CvImage.java:111)
            at org.ros.android.android_tutorial_cv_bridge.MainActivity$1.onNewMessage(MainActivity.java:134)
            at org.ros.android.android_tutorial_cv_bridge.MainActivity$1.onNewMessage(MainActivity.java:128)
            at org.ros.internal.transport.queue.MessageDispatcher$1.run(MessageDispatcher.java:94)
            at org.ros.internal.transport.queue.MessageDispatcher$1.run(MessageDispatcher.java:91)
            at org.ros.concurrent.EventDispatcher.loop(EventDispatcher.java:43)
            at org.ros.concurrent.CancellableLoop.run(CancellableLoop.java:56)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
08-21 23:40:32.934  19717-19729/org.ros.android.android_tutorial_cv_bridge E/art﹕ No implementation found for void org.opencv.core.Mat.n_delete(long) (tried Java_org_opencv_core_Mat_n_1delete and Java_org_opencv_core_Mat_n_1delete__J)
08-21 23:40:32.935  19717-19729/org.ros.android.android_tutorial_cv_bridge E/System﹕ Uncaught exception thrown by finalizer
08-21 23:40:32.935  19717-19729/org.ros.android.android_tutorial_cv_bridge E/System﹕ java.lang.UnsatisfiedLinkError: No implementation found for void org.opencv.core.Mat.n_delete(long) (tried Java_org_opencv_core_Mat_n_1delete and Java_org_opencv_core_Mat_n_1delete__J)
            at org.opencv.core.Mat.n_delete(Native Method)
            at org.opencv.core.Mat.finalize(Mat.java:2475)
            at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:191)
            at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:174)
            at java.lang.Thread.run(Thread.java:818)

**Comment by kejriwalnishant1990** [comment]
is with working fine on your machine?

**Comment by kejriwalnishant1990** [comment]
is it working fine on your machine?

**Comment by talregev** [comment]
yes. is working good on my phones.

try to find this line:
classpath "com.android.tools.build:gradle:1.3.1"
to this line:
classpath "com.android.tools.build:gradle:1.2.3"

there is 3 lines like this in the code.

**Comment by talregev** [comment]
are you using real phone or simulator?

**Comment by kejriwalnishant1990** [comment]
real phone Nexus 4 Lollipop

**Comment by talregev** [comment]
I also use Lollipop, on HTC one m7

**Comment by kejriwalnishant1990** [comment]
Still i am getting same error:

8-21 23:46:41.904  23832-23832/org.ros.android.android_tutorial_cv_bridge D/CameraBridge﹕ Attr count: 5
08-21 23:46:41.939  23832-23880/org.ros.android.android_tutorial_cv_bridge D/OpenGLRenderer﹕ Use EGL_SWAP_BEHAVIOR_PRESERVED: true
08-21 23:46:41.948  23832-23832/org.ros.android.android_tutorial_cv_bridge D/Atlas﹕ Validating map...
08-21 23:46:42.034  23832-23880/org.ros.android.android_tutorial_cv_bridge I/Adreno-EGL﹕ <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 01/15/15, ab0075f, Id3510ff6dc
08-21 23:46:42.036  23832-23880/org.ros.android.android_tutorial_cv_bridge I/OpenGLRenderer﹕ Initialized EGL, version 1.4
08-21 23:46:42.078  23832-23880/org.ros.android.android_tutorial_cv_bridge D/OpenGLRenderer﹕ Enabling debug mode 0
08-21 23:46:45.321  23832-23842/org.ros.android.android_tutorial_cv_bridge W/art﹕ Suspending all threads took: 82.649ms
08-21 23:46:45.618  23832-24154/org.ros.android.android_tutorial_cv_bridge I/Registrar﹕ MasterXmlRpcEndpoint URI: http://192.168.1.6:11311/
08-21 23:46:45.648  23832-24164/org.ros.android.android_tutorial_cv_bridge I/Registrar﹕ Registering publisher: Publisher<PublisherDefinition<PublisherIdentifier<NodeIdentifier</android_tutorial_cv_bridge, http://192.168.1.4:52410/>, TopicIdentifier</rosout>>, Topic<TopicIdentifier</rosout>, TopicDescription<rosgraph_msgs/Log, acffd30cd6b6de30f120938c17c593fb>>>>
08-21 23:46:45.936  23832-24167/org.ros.android.android_tutorial_cv_bridge I/Registrar﹕ Response<Success, Registered [/android_tutorial_cv_bridge] as publisher of [/rosout], [http://192.168.1.6:58640/]>
08-21 23:46:45.938  23832-24165/org.ros.android.android_tutorial_cv_bridge I/DefaultPublisher﹕ Publisher registered: Publisher<PublisherDefinition<PublisherIdentifier<NodeIdentifier</android_tutorial_cv_bridge, http://192.168.1.4:52410/>, TopicIdentifier</rosout>>, Topic<TopicIdentifier</rosout>, TopicDescription<rosgraph_msgs/Log, acffd30cd6b6de30f120938c17c593fb>>>>
08-21 23:46:45.942  23832-24157/org.ros.android.android_tutorial_cv_bridge I/Registrar﹕ Registering publisher: Publisher<PublisherDefinition<PublisherIdentifier<NodeIdentifier</android_tutorial_cv_bridge, http://192.168.1.4:52410/>, TopicIdentifier</image/pub>>, Topic<TopicIdentifier</image/pub>, TopicDescription<sensor_msgs/Image, 060021388200f6f0f447d0fcd9c64743>>>>
08-21 23:46:45.955  23832-24157/org.ros.android.android_tutorial_cv_bridge I/Registrar﹕ Registering subscriber: Subscriber<Topic<TopicIdentifier</usb_cam/image_raw>, TopicDescription<sensor_msgs/Image, 060021388200f6f0f447d0fcd9c64743>>>
08-21 23:46:45.956  23832-24200/org.ros.android.android_tutorial_cv_bridge I/Registrar﹕ Response<Success, Registered [/android_tutorial_cv_bridge] as publisher of [/image/pub], []>
08-21 23:46:45.957  23832-24167/org.ros.android.android_tutorial_cv_bridge I/DefaultPublisher﹕ Publisher registered: Publisher<PublisherDefinition<PublisherIdentifier<NodeIdentifier</android_tutorial_cv_bridge, http://192.168.1.4:52410/>, TopicIdentifier</image/pub>>, Topic<TopicIdentifier</image/pub>, TopicDescription<sensor_msgs/Image, 060021388200f6f0f447d0fcd9c64743>>>>
08-21 23:46:45.961  23832-24157/org.ros.android.android_tutorial_cv_bridge I/cv_bridge Tutorial﹕ called onStart
08-21 23:46:45.971  23832-24206/org.ros.android.android_tutorial_cv_bridge I/Registrar﹕ Response<Success, Subscribed to [/usb_cam/image_raw], [http://192.168.1.6:43357/]>
08-21 23:46:45.973  23832-24203/org.ros.android.android_tutorial_cv_bridge I/DefaultSubscriber﹕ Subscriber registered: Subscriber<Topic<TopicIdentifier</usb_cam/image_raw>, TopicDescription<sensor_msgs/Image, 060021388200f6f0f447d0fcd9c64743>>>
08-21 23:46:46.255  23832-23842/org.ros.android.android_tutorial_cv_bridge W/art﹕ Suspending all threads took: 16.053ms
08-21 23:46:46.917  23832-24208/org.ros.android.android_tutorial_cv_bridge E/art﹕ No implementation found for long org.opencv.core.Mat.n_Mat(int, int, int) (tried Java_org_opencv_core_Mat_n_1Mat and Java_org_opencv_core_Mat_n_1Mat__III)
08-21 23:46:46.918  23832-24208/org.ros.android.android_tutorial_cv_bridge E/AndroidRuntime﹕ FATAL EXCEPTION: pool-1-thread-18
    Process: org.ros.android.android_tutorial_cv_bridge, PID: 23832
    java.lang.UnsatisfiedLinkError: No implementation found for long org.opencv.core.Mat.n_Mat(int, int, int) (tried Java_org_opencv_core_Mat_n_1Mat and Java_org_opencv_core_Mat_n_1Mat__III)
            at org.opencv.core.Mat.n_Mat(Native Method)
            at org.opencv.core.Mat.<init>(Mat.java:477)
            at cv_bridge.CvImage.matFromImage(CvImage.java:351)
            at cv_bridge.CvImage.toCvCopy(CvImage.java:111)
            at org.ros.android.android_tutorial_cv_bridge.MainActivity$1.onNewMessage(MainActivity.java:134)
            at org.ros.android.android_tutorial_cv_bridge.MainActivity$1.onNewMessage(MainActivity.java:128)
            at org.ros.internal.transport.queue.MessageDispatcher$1.run(MessageDispatcher.java:94)
            at org.ros.internal.transport.queue.MessageDispatcher$1.run(MessageDispatcher.java:91)
            at org.ros.concurrent.EventDispatcher.loop(EventDispatcher.java:43)
            at org.ros.concurrent.CancellableLoop.run(CancellableLoop.java:56)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
08-21 23:46:47.231  23832-23845/org.ros.android.android_tutorial_cv_bridge E/art﹕ No implementation found for void org.opencv.core.Mat.n_delete(long) (tried Java_org_opencv_core_Mat_n_1delete and Java_org_opencv_core_Mat_n_1delete__J)
08-21 23:46:47.231  23832-23845/org.ros.android.android_tutorial_cv_bridge E/System﹕ Uncaught exception thrown by finalizer
08-21 23:46:47.232  23832-23845/org.ros.android.android_tutorial_cv_bridge E/System﹕ java.lang.UnsatisfiedLinkError: No implementation found for void org.opencv.core.Mat.n_delete(long) (tried Java_org_opencv_core_Mat_n_1delete and Java_org_opencv_core_Mat_n_1delete__J)
            at org.opencv.core.Mat.n_delete(Native Method)
            at org.opencv.core.Mat.finalize(Mat.java:2475)
            at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:191)
            at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:174)
            at java.lang.Thread.run(Thread.java:818)

**Comment by talregev** [comment]
you download this?
https://play.google.com/store/apps/details?id=org.opencv.engine
you need opencv on your  phone.

**Comment by kejriwalnishant1990** [comment]
But you have provided opencv in this library. Do i need to install separately?

**Comment by talregev** [comment]
yes. of course. my program provide connect to the library, not the opencv itself.
Maybe you can add this to the Wiki ...

**Comment by kejriwalnishant1990** [comment]
should i revert the changes?

**Comment by talregev** [comment]
mmm
yes, and if it not work then change again. slowly.

**Comment by kejriwalnishant1990** [comment]
Ok now code is running, but when i am trying to see image on pc from this command:
$ rosrun image_view image_view image:=/image/pub
I am getting following error:
 Unable to convert 'rgb8' image to bgr8: 'Image is wrongly formed: step < width \* byte_depth \* num_channels  or  640 != 640 \* 1 \* 3'

**Comment by kejriwalnishant1990** [comment]
/image/pub is rostopic for publisher

**Comment by talregev** [comment]
you have rviz?

**Comment by kejriwalnishant1990** [comment]
yes

**Comment by talregev** [comment]
check on rviz.

**Comment by talregev** [comment]
did you change the code, or is the original?

**Comment by kejriwalnishant1990** [comment]
I have checked on changed code.... Should i try with original code?

**Comment by talregev** [comment]
yes. but this message will not gone. 
It other problem.

**Comment by kejriwalnishant1990** [comment]
Does this message comes on your machine also?

**Comment by talregev** [comment]
I check on rviz, not with image_view

**Comment by kejriwalnishant1990** [comment]
In rviz, the image is coming out correctly. Now i am checking everything with original code.

**Comment by talregev** [comment]
thanks.

**Comment by kejriwalnishant1990** [comment]
It works with original code too.. thanks a lot. 
Currently frame speed is slow, i think compress image will work on higher frame per second.

**Comment by talregev** [comment]
Thanks for checking. 
Yes, but compress image not finish.
If you can, and it help me a lot,
To update the Wiki, and Here ReadMe file.

Need still to investigate why the step is not calculate correctly on msgs. you can look on it if you like and sumbit a patch.

**Comment by kejriwalnishant1990** [comment]
I will definitley update wiki page and ReadMe file.

**Comment by talregev** [comment]
Thanks :) :+1:

**Comment by kejriwalnishant1990** [comment]
I want to change graphical interface in android_10 library. is it possbile to do in your code?

**Comment by talregev** [comment]
It not my code.
It android core code. you will need to re-compile it.

**Comment by kejriwalnishant1990** [comment]
Why u have used JavaCameraView in main.xml?

**Comment by talregev** [comment]
You can delete this. It from old code.
If it ok, i will remove it myself.

**Comment by kejriwalnishant1990** [comment]
I want to display subscribed image in my phone. Is it possible? 
I tried using ImageView but it is throwing error OpenCV_for_Tegra﹕ Cannot create OpenGL context

**Comment by kejriwalnishant1990** [comment]
I am using this code:

``` java
Bitmap bmp = null;
bmp = Bitmap.createBitmap(cvImage.image.cols(), cvImage.image.rows(), Bitmap.Config.ARGB_8888);
Utils.matToBitmap(cvImage.image, bmp);
Im.setImageBitmap(bmp);
```

**Comment by talregev** [comment]
It possible, but It difficult. I read some code example on stack over flaw. 
But I fell to do it.
If you succeeded, just pull request your code to here.

**Comment by kejriwalnishant1990** [comment]
have you seen camera_image_tutorial in android core? In that code, they are displaying the image also.

**Comment by talregev** [comment]
To display image from camera is easy. but to display your own image (from topic) it more  challenge.

**Comment by talregev** [comment]
What is Im in:
`Im.setImageBitmap(bmp);`?

**Comment by kejriwalnishant1990** [comment]
``` java
public ImageView Im;        
Im = (ImageView) findViewById(R.id.imageView1);
```

**Comment by talregev** [comment]
Which type should be `imageView1`?

**Comment by kejriwalnishant1990** [comment]
In main.xml

``` xml
 <ImageView
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        android:id="@+id/imageView1"
        android:layout_gravity="center_horizontal" />
```

**Comment by talregev** [comment]
I already check the example, from [here](http://www.mkyong.com/android/android-imageview-example/)
Maybe i can do it.

**Comment by kejriwalnishant1990** [comment]
Are you trying to display image? If you are sucessfull, let me know.
I am getting OpenGL error.

**Comment by talregev** [comment]
Just to show the user the image alter using the opencv.
I will update the cv_bridge library code.

**Comment by kejriwalnishant1990** [comment]
I didnt get you. Are you adding a patch for displaying image in android?

**Comment by talregev** [comment]
It will be difficult:
`Only the original thread that created a view hierarchy can touch its views`

**Comment by kejriwalnishant1990** [comment]
You have to run this thread in parallel.

**Comment by talregev** [comment]
i do this code:

``` java
runOnUiThread(new Runnable() {
    @Override
    public void run() {
          // This code will always run on the UI thread, therefore is safe to modify UI elements.
          imageView.setImageBitmap(bmp);
    }
});
```

but it dose show the image, and good thing it not crash.

**Comment by talregev** [comment]
I succeeded to show the subscribed images on the phone with the circle (that one that will send).

**Comment by kejriwalnishant1990** [comment]
I am also able to subscribe the images in cv_bridge tutorial.
But in compress image tutorial, images in phone are not displayed properly. Is it working fine with you?

**Comment by talregev** [comment]
Now I fix the CvCompressedImages :)
The basic functionality is working well!! :)

**Comment by talregev** [comment]
If It works for you, I will close this issue.

**Comment by kejriwalnishant1990** [comment]
Yes. it is working fine for me. Thanks

**Comment by talregev** [comment]
@kejriwalnishant1990 
I write a new library, and a new apss, that don't use opencv manager.
