### ISSUE TITLE
Is it possible to transport a local image (from SD card) to ROS in android_cv_bridge way?

### ISSUE THREAD

**Issue by frank0123** [talregev/android_cv_bridge#4]
Hi, @talregev ! I'm new to _**ros**_ and, recently I need transport a _**local image(from SD card)**_ to ROS in android. I know I should transport it by the _**cv_bridge**_, and I had import the _**OpenCV-for-Android**_ package in my Android Studio. However, I don't know how to make a local image transformed into _**CvImage**_ by OpenCV, and finally make it to _**sensor_msgs.Image/CompressedImage**_ messages. Do you have a good suggestion to make this possible?

My idea is something like this:
           
            filePath = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES).toString() + "xxx.jpg";
            try {
                fileInputStream = new FileInputStream(filePath);
            }
            catch (IOException e) {
                e.printStackTrace();
            }

            bmp = BitmapFactory.decodeStream(fileInputStream);

            // compress
            byteArrayOutputStream = new ByteArrayOutputStream();
            bmp.compress(Bitmap.CompressFormat.JPEG, 200, byteArrayOutputStream);

            int quality = 200;
            while (byteArrayOutputStream.toByteArray().length / 1024 > 200) {
                byteArrayOutputStream.reset();
                bmp.compress(Bitmap.CompressFormat.JPEG, quality, byteArrayOutputStream);
                quality -= 10;
            }

            byteArrayInputStream = new ByteArrayInputStream(byteArrayOutputStream.toByteArray());
            bmp = BitmapFactory.decodeStream(byteArrayInputStream, null, null);
            channelBufferOutputStream.buffer().writeBytes(byteArrayOutputStream.toByteArray());

            // bmp to mat
            mat_image = new Mat();
            Bitmap copyBmp = bmp.copy(Bitmap.Config.ARGB_8888, false);
            Utils.bitmapToMat(copyBmp, mat_image);

What about the next to deal with the _**mat_image**_ (or other way) ?

**Comment by frank0123** [comment]
I had worked it out! Android_CV_Bridge is really a good way, thanks again!

**Comment by talregev** [comment]
@frank0123 thanks!

**Comment by talregev** [comment]
For answer, It better to load the images from sdcard with opencv imread.   
```Java
Mat m = Highgui.imread("/media/path_to_image");
```
This method load the image it transform it to Mat image.
```Java
CvImage cvImage(Header(), "rgb8", m);
cvImage.toCompressedImageMsg(imagePublisher.newMessage(), Format.JPG);
```
Then use android_cv_bridge to transform it to ros image compress message.
